# 딥러닝을 위한 PyTorch 활용법
## Chapter 2. Linear Regression & Neural Network

## 1. Variable & Automatic Gradient Calculation

In [1]:
import torch
from torch.autograd import Variable

In [8]:
x_tensor = torch.Tensor(3,4)
x_tensor.data

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Variable

In [17]:
# 위에 생성한 tensor와 똑같아 보이지만 Variable이라는 클라쓰에 감싸져있음
# 현재 버젼(4.1)에는 그냥 tensor도 Variable이랑 같음(기능 추가)
x_variable = Variable(x_tensor)
print(x_variable)
print(x_variable.data)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### Gradient

In [23]:
# .grad -> 해당 tensor(or variable)에 대한 gradient를 출력한다.
print(x_variable.grad) # 연산이 없기 때문에 None

None


### Requires Gradient

In [25]:
# .requires_grad -> gradient를 만들지 여부를 설정한다.
print(x_variable.requires_grad)

x_variable = Variable(x_tensor, requires_grad = True) # 여부 True
print(x_variable.requires_grad)

False
True


### Volatile mode(지금은 바뀜)
- 불필요한 계산 없이 테스트 용으로 전환해준다.(Inference mode)
- 결과를 빠르게 알 수 있다.
- 하나의 variable에 volatile = True가 있으면 전체에 적용된다.
- **volatile은 없어지고 torch.no_grad()로 바뀜**

In [53]:
x_variable = Variable(x_tensor)
print(torch.no_grad)
print(x_variable.grad, x_variable.requires_grad)

<class 'torch.autograd.grad_mode.no_grad'>
None False


### Graph & Variable
- 연산그래프 만들기

In [67]:
x = Variable(torch.FloatTensor(3,4), requires_grad = True)
y = x**2 + 4*x
z = 2*y + 3
x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [68]:
# backward(gradient, retain_graph, create_graph, retain_variables)
# 역전파를 자동으로 해주는 함수
# gradient를 계산하는데 현재 존재하는 변수들의 leaves에는 저장하겠다.
# 따라서 x에만 기울기가 있고 나머지 y, z에는 없다. 

loss = torch.FloatTensor(3,4) # 임의로 랜덤값으로 초기화함
z.backward(loss) # z값에 대하여 역전파를 하여라, loss값은 loss가 나왔다.

print(x.grad)
print(y.grad)
print(z.grad)

# y,z가 모두 x로 표현될 수 있기 때문에

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
None
None
