# 딥러닝을 위한 PyTorch 활용법
## Chapter 1. 딥러닝과 PyTorch

### Random numbers

In [3]:
import torch

# torch.rand(sizes) = [0,1]
x = torch.rand(2,3)
x

tensor([[0.5621, 0.4755, 0.1843],
        [0.6641, 0.6515, 0.9100]])

In [5]:
# torch.randn(sizes) = Z(0,1)
x = torch.randn(2,3)
x

tensor([[-0.0779, -1.0393, -0.0160],
        [-0.5582,  1.0954, -1.0240]])

In [7]:
# torch.randperm(n) = permutation(순열) of 0 ~ n
x = torch.randperm(5)
x

tensor([4, 2, 3, 0, 1])

### zeros, ones, arange

In [9]:
# torch.zeros(2,3) = [[0, 0, 0,], [0, 0, 0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# torch.ones(2,3) = [1[1,1,1], [1,1,1]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# torch.arange(start, end, step = 1) = (start, end) with step
x = torch.arange(0, 3, step = 0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

### Tensor Data Type

In [14]:
# torch.FloatTensor(size or list) << Default
x = torch.FloatTensor(2,3)
x

tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [16]:
x = torch.FloatTensor([2,3]) # 값이 들어감, list 형식
x

tensor([2., 3.])

In [18]:
# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### Numpy to Tensor, Tensor to Numpy

In [27]:
import numpy as np

# torch.from_numpy(ndarray) -> tensor

# x1 = np.array([1,2,3,4,5,6], dtype = int)
x1 = np.ndarray(shape = (2,3), dtype = int, buffer = np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [28]:
# tensor.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

### Tensor on CPU & GPU
- CPU에서 사용하던 tensor를 GPU에 올리기

In [29]:
x = torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [30]:
# torch.cuda(n) = GPU로 tensor 올리기, n은 GPU의 index, default = 0
x_gpu = x.cuda() 
x_gpu

RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at ..\aten\src\THC\THCGeneral.cpp:74

In [31]:
# torch.cpu() = CPU로 tensor 내리기
x_cpu = x_gpu.cpu()

NameError: name 'x_gpu' is not defined

### Tensor Size
- 그래프를 만들다 보면 연산 후 모양이 어떤지 궁금함

In [32]:
# tensor.size() -> 인덱싱도 가능하다
x = torch.FloatTensor(10, 12, 3, 3)
x.size()

torch.Size([10, 12, 3, 3])

### Indexing, Slicing, Joining

**indexing**

In [35]:
# torch.index_select(input, dim, index)
x = torch.rand(4,3)
out = torch.index_select(x, 0, torch.LongTensor([0,3]))

print(x)
print(out)

tensor([[0.7091, 0.6830, 0.5382],
        [0.9306, 0.8577, 0.8490],
        [0.3654, 0.6176, 0.4440],
        [0.1481, 0.8417, 0.8748]])
tensor([[0.7091, 0.6830, 0.5382],
        [0.1481, 0.8417, 0.8748]])


In [39]:
# Pythonic indexing also works
print(x[:,0])
print(x[0,:])
print(x[0:2, 0:2])

tensor([0.7091, 0.9306, 0.3654, 0.1481])
tensor([0.7091, 0.6830, 0.5382])
tensor([[0.7091, 0.6830],
        [0.9306, 0.8577]])


In [41]:
# torch.masked_select(input, mask) -> mask모양으로 찍어내기

x = torch.rand(2,3)
mask = torch.ByteTensor([[0,0,1], [1,0,0]])
out = torch.masked_select(x, mask)

print(x)
print(mask)
print(out)

tensor([[0.3086, 0.1570, 0.8154],
        [0.5833, 0.2301, 0.3785]])
tensor([[0, 0, 1],
        [1, 0, 0]], dtype=torch.uint8)
tensor([0.8154, 0.5833])


**Joining**

In [42]:
# torch.cat(seq, dim = 0) -> concatenate tensor along dim
# dim = 0 -> 행으로 추가(행 개수 증가)
# dim = 1 -> 열에 추가(열 개수 증가)
x = torch.FloatTensor([[1,2,3], [4,5,6]])
y = torch.FloatTensor([[-1,-2,-3], [-4,-5,-6]])
z1 = torch.cat([x,y], dim = 0)
z2 = torch.cat([x,y], dim = 1)

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])


In [44]:
# torch.stack(sequence, dim = 0) -> 새로운 dim으로 합치기

x = torch.FloatTensor([[1,2,3], [4,5,6]])
x_stack = torch.stack([x,x,x,x], dim = 0)
x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

**Slicing**

In [55]:
# torch.chunk(tensor, chunks, dim = 0) -> tensor into num chunks(덩어리)

z1 = torch.FloatTensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
x_1, x_2 = torch.chunk(z1, 2, dim = 0)
y_1, y_2, y_3 = torch.chunk(z1, 3, dim = 1)

print(z1)
print(x_1)
print(x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [59]:
# torch.split(tensor, split_size, dim) -> split into specific size

x1, x2 = torch.split(z1, 2, dim = 0)
y1 = torch.split(z1, 2, dim = 1)

print(z1)
print(x1)
print(x2)
print(y1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
(tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]]), tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]]))


**squeezing**

In [78]:
# torch. squeeze(input, dim = None) -> reduce dim by 1

x1 = torch.FloatTensor(10, 1, 3, 1, 4)
x2 = torch.squeeze(x1)

print(x1.size())
print(x2.size())

torch.Size([10, 1, 3, 1, 4])
torch.Size([10, 3, 4])


In [88]:
# torch.unsqueeze(input, dim = None) -> add dim by 1

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1, dim = 0)

print(x1.size())
print(x2.size())

torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


### Initialization
- Tensor가 처음에는 랜덤값으로 생성된다.
- 각각 원하는 폼의 랜덤값으로 생성하고 싶을 때 사용
- torch.nn.init 모듈 사용
- 현재 버젼에서는 torch.nn.init.uniform_ : 언더바 하나 적는걸로 바뀜
- uniform_, normal_, constant_

In [96]:
import torch.nn.init as init

x1 = init.uniform_(torch.FloatTensor(3,4), a = 0, b = 9) # 0 ~ 9
x2 = init.normal_(torch.FloatTensor(3,4), std = 0.2)
x3 = init.constant_(torch.FloatTensor(3,4), 3.1415)

print(x1)
print(x2)
print(x3)

tensor([[7.4150, 6.5874, 8.2181, 1.1966],
        [2.4105, 8.4881, 8.6417, 2.8228],
        [5.2752, 2.9946, 3.3573, 7.8744]])
tensor([[ 0.0860, -0.2481, -0.0191,  0.0136],
        [-0.2351, -0.2977,  0.1147, -0.2699],
        [-0.0888,  0.0749, -0.3740,  0.0252]])
tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]])


### Operation
- 기존에 쓰던 방식(사칙연산)으로 그냥 쓰면 된다.
- boradcast을 지원하기 때문에(numpy처럼)
- exp, log, mm, bmm